In [1]:
#Práctica: Evaluación de la Calidad de un Modelo de Machine Learning


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_iris


#Cargar y Entrenar Modelo
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

#Generamos la predicción 
y_pred = model.predict(X_test)

# Callculamos la precisión 
accuracy = accuracy_score(y_test, y_pred)
print(f'Precisión del modelo: {accuracy:.2f}')



# Matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(conf_matrix)

# Informe de clasificación
class_report = classification_report(y_test, y_pred, target_names=iris.target_names)
print('Informe de Clasificación:')
print(class_report)

Precisión del modelo: 1.00
Matriz de Confusión:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Informe de Clasificación:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
# los resultados reflejan precisión y exactitud al 100%, no hay error , se pude considerar que presenta un overfitting 